client:
	g++ -std=c++11 -O3 *.cpp main/client_main.cpp Fib2584/*.cpp -o ai_client

stdio:
	g++ -std=c++11 -O3 *.cpp main/main.cpp Fib2584/*.cpp -o ai_stdio

train:
	g++ -std=c++11 -O3 *.cpp main/train_main.cpp Fib2584/*.cpp -o ai_train
